dist: trusty

language: cpp

cache: ccache

compiler:
  - clang
  - gcc

git:
    depth: 3

addons:
  apt:
    packages:
      - libboost-dev
      - libboost-test-dev
      - flex
      - valgrind
      - lcov
      - swig
      - python3
      - python3-dev

script:
  - ccache -s
  - cmake -DBUILD_TESTING=ON -DBUILD_COVERAGE=ON
  - export LD_LIBRARY_PATH=$PWD/lib:$PWD/thirdparty/lib:$PWD/python:$LD_LIBRARY_PATH
  - export PYTHONPATH=$PWD/lib:$PWD/python
  - make -j $(nproc)
  - ctest -T memcheck
  - if [ "$CXX" == "g++"     ]; then ./lcov.bash; fi
  - if [ "$CXX" == "clang++" ]; then make test; fi
  - ccache -s

after_success:
  - bash <(curl -s https://codecov.io/bash)
